### Read All
GET http://localhost:8080/article

### Get One
GET http://localhost:8080/article/1

### Create One
POST http://localhost:8080/article
Content-Type: application/json

{
  "name": "Article Three"
}

### Update One
PUT http://localhost:8080/article
Content-Type: application/json

{
  "article_id" : 1,
  "name": "Article Four"
}

### Delete One
DELETE http://localhost:8080/article
Content-Type: application/json

{
  "article_id" : 1,
  "name": "Article Four"
}
