### LOGIN
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "gab@test.com",
  "password": "Sup3rS3cur3!"
}

### VERIFY TOKEN
POST http://localhost:8080/auth/verify
Content-Type: text/plain

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJhdXRoMCIsImVtYWlsIjoiZ2FiQHRlc3QuY29tIn0.-Aps_mOyE2Bg46ibz6we2PEuAd5jXRTeA_--QrNV9AcdaFb0pXgW9hb8GyuT4LNvagmCgAZp--8Rh0JgI4Qn5A