//à lancer après le script test users

### LOGIN
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "mail": "ju",
  "password": "ju"
}

### VERIFY TOKEN
POST http://localhost:8080/auth/verify
Content-Type: text/plain

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJtYWlsIjoianUiLCJpc3MiOiJhdXRoMCJ9.BGXmdNYymA1dzvyAqr_o4Z8-6SPmdaWY8pklPqy1pTowtaFPuEYgCefw-3HDc8zc68OCTJohnyRr9y8wrFiN5w