###
### Basé sur le cript SQL
###

### Read all
GET http://localhost:8080/client

### Get One
GET http://localhost:8080/client/1

### Get One with bad id
GET http://localhost:8080/client/-1



### Create One
POST http://localhost:8080/client
Content-Type: application/json

{
  "address": "123 Main St, City1",
  "name": "Client Three",
  "phoneNumber": "111222333",
  "childrenQuantity": 2,
  "tour": 1
}


### Create One user with a tour that doesn't exist
POST http://localhost:8080/client
Content-Type: application/json

{
  "address": "123 Main St, City1",
  "name": "Client Three",
  "phoneNumber": "111222333",
  "childrenQuantity": 2,
  "tour": 1000
}



### Update One
PUT http://localhost:8080/client/1
Content-Type: application/json

{
  "id": 1,
  "address": "123 Main St, City1",
  "name": "Client Four",
  "phoneNumber": "111222333",
  "childrenQuantity": 2,
  "tour": 1
}


### Update One with bad id (not matching with the body one)
PUT http://localhost:8080/client/3
Content-Type: application/json

{
  "id": 1,
  "address": "123 Main St, City1",
  "name": "Client Four",
  "phoneNumber": "111222333",
  "childrenQuantity": 2,
  "tour": 1
}