###
### Basé sur le cript SQL
###

### Read all
GET http://localhost:8080/client
### Get One
GET http://localhost:8080/client/1


### Create One
POST http://localhost:8080/client
Content-Type: application/json

{
  "address": "123 Main St, City1",
  "name": "Client Three",
  "phoneNumber": "111222333",
  "childrenQuantity": 2,
  "tour": 1
}



### Update One
PUT http://localhost:8080/client/1
Content-Type: application/json

{
  "id": 1,
  "address": "123 Main St, City1",
  "name": "Client Four",
  "phoneNumber": "111222333",
  "childrenQuantity": 2,
  "tour": 1
}