# Création d'une exécution de tour
###ajout d un tour-execution
POST http://localhost:8080/tour/1/tourExecution
Content-Type: application/json

{
  "executionDate": "2024-07-20",
  "state": "prévue",
  "deliveryPerson": "admin@example.com",
  "vehicleId": 2,
  "tourId": 1
}




### Récupération des exécutions de tour pour un tour et un état donnés
GET http://localhost:8080/tour/1/prévue
Content-Type: application/json

### Récupération des exécutions de tour pour un tour, un livreur et un état donnés
GET http://localhost:8080/tour/1/user/admin@example.com/state/prévue
Content-Type: application/json


###maj deliveryPerson d un tour-execution
PATCH http://localhost:8080/tour/1/tourExecution/deliveryPerson
Content-Type: application/json

{
  "mail": "user2@example.com",
  "firstname": "User",
  "lastname": "two",
  "phoneNumber": "987654321",
  "isAdmin": false
}

###maj camionette d un tour-execution
PATCH http://localhost:8080/tour/2/tourExecution/van
Content-Type: application/json

{
  "id": 1,
  "name": "Van A",
  "plate": "ABC123",
  "maxQuantity": 10
}

###maj state d un tour execution ( commencee )
POST http://localhost:8080/tour/1/tourExecution/begin

###maj state d un tour execution ( finie )
POST http://localhost:8080/tour/2/tourExecution/end

###
POST http://localhost:8080/tour/1/tourExecution/end

### ajouter du surplus à une tour executon
POST http://localhost:8080/tour/1/addSurplus
Content-Type: application/json

{
  "articleId": 1,
  "tourExecutionId": 1,
  "percentage": 10
}

### get all articlss for tourExex
GET http://localhost:8080//tour/1/tourExecution/allArticles

### get all client for tourExex
GET http://localhost:8080//tour/1/tourExecution/allClients

