### Read All Tours
GET http://localhost:8080/tour

### Get One Tour
GET http://localhost:8080/tour/1

### Create One Tour
POST http://localhost:8080/tour
Content-Type: application/json

{
  "name": "Tour Three"
}

### Update One Tour
PUT http://localhost:8080/tour/1
Content-Type: application/json

{
  "id" : 1,
  "name": "Tour Four"
}


### Create Tour Order
POST http://localhost:8080/tour/3/createTourOrder
Content-Type: application/json

[
{"clientId": 3, "tourId": 3, "order": 1},
{"clientId": 4, "tourId": 3, "order": 2}
]


### Create Tour Order with a client from an other tour
POST http://localhost:8080/tour/3/createTourOrder
Content-Type: application/json

[
  {"clientId": 3, "tourId": 3, "order": 1},
  {"clientId": 4, "tourId": 3, "order": 2},
  {"clientId": 1, "tourId": 3, "order": 3}
]


### Create Tour Order with wrong order (2 same orders)
POST http://localhost:8080/tour/2/createTourOrder
Content-Type: application/json

[
  {"clientId": 1, "tourId": 2, "order": 2},
  {"clientId": 2, "tourId": 2, "order": 2}
]

### Modify Tour Order
PUT http://localhost:8080/tour/3/modifyTourOrder
Content-Type: application/json

[
  {"clientId": 3, "tourId": 3, "order": 2},
  {"clientId": 4, "tourId": 3, "order": 1}
]


### Modify client 2 to make him in the Tour A
PUT http://localhost:8080/client/2
Content-Type: application/json

{
  "id": 2,
  "address": "456 Oak St, City2",
  "name": "Client Two",
  "phoneNumber": "444555666",
  "childrenQuantity": 3,
  "tour": 1
}

###Modify Tour Order to add this updated client
PUT http://localhost:8080/tour/1/modifyTourOrder
Content-Type: application/json

[
{"clientId":2,"tourId":1,"order":1},
  {"clientId":1,"tourId":1,"order":2}
]


### Read Tour Order
GET http://localhost:8080/tour/2/getTourOrder