###
### Basé sur le cript SQL
###

### Read all
GET http://localhost:8080/user

### Get One
GET http://localhost:8080/user/user1@example.com


### Create One
POST http://localhost:8080/user
Content-Type: application/json

{
  "email": "ju",
  "firstname": "ju",
  "lastname": "ju",
  "phoneNumber": "5589825",
  "isAdmin": true,
  "password": "ju"
}



### Update One
PUT http://localhost:8080/user/ju
Content-Type: application/json

{
  "mail": "ju",
  "firstname": "Roy",
  "lastname": "Agbassah",
  "phoneNumber": "5589825",
  "isAdmin": true
}

###Get all delivery men
GET http://localhost:8080/user/delivery