###
### Basé sur le cript SQL
###

### Read all
GET http://localhost:8080/user
### Get One
GET http://localhost:8080/user/user1@example.com


### Create One
POST http://localhost:8080/user
Content-Type: application/json

{
  "user_data" : {
    "mail": "steven@gmail.com",
    "firstname": "Steven",
    "lastname": "Agbassah",
    "phoneNumber": "5589825",
    "isAdmin" : true

  },
  "password" : "passwordtest"

}



### Update One
PUT http://localhost:8080/user/steven@gmail.com
Content-Type: application/json

{
  "mail": "steven@gmail.com",
  "firstname": "Roy",
  "lastname": "Agbassah",
  "phoneNumber": "5589825",
  "isAdmin" : true

}