### Read All
GET http://localhost:8080/vehicle

### Get One
GET http://localhost:8080/vehicle/1

### Create One
POST http://localhost:8080/vehicle
Content-Type: application/json

{
  "name": "Vehicle Three",
  "plate": "ABC123",
  "maxQuantity": 5
}

### Update One
PUT http://localhost:8080/vehicle/1
Content-Type: application/json

{
  "id": 1,
  "name": "Vehicle Four",
  "plate": "ABC123",
  "maxQuantity": 5
}


